stages:
  - test
  - build

test:
  stage: test
  image: alpine:latest
  script:
    - echo "CI works"
    - uname -a
    - echo "Tests passed"

build:
  stage: build
  image: alpine:latest
  script:
    - echo "Build stage: packing repository"
    - tar -czf artifact.tar.gz .
  artifacts:
    paths:
      - artifact.tar.gz
    expire_in: 1 week
